from datetime import datetime
import subprocess

now = datetime.now()  # current date and time
file_name = now.strftime("%m-%d-%Y - %H:%M") + "-scan.txt"
print(file_name)

with open(file_name, "w") as file:
    file.write("1. Отчёт о состоянии системы: \n")
    output = subprocess.check_output('lscpu', shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")

    file.write("2. Пользователи системы: \n")
    output = subprocess.check_output(['cat /etc/passwd'], shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")

    file.write("3. Процессов запущено: ")
    output = subprocess.check_output(['ps -e | wc -l'], shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")

    file.write("4. Пользовательских процессов: \n")
    file.write("   root: ")
    output = subprocess.check_output(['sudo ps -U root | wc -l'], shell=True)
    file.write("   user: ")
    output = subprocess.check_output(['sudo ps -U user1 | wc -l'], shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")

    file.write("5. Всего памяти используется: ")
    output = subprocess.check_output(['used -m'], shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")

    file.write("6. Всего CPU используется: ")
    output = subprocess.check_output(['top'], shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")

    file.write("7. Больше всего памяти использует:  ")
    output = subprocess.check_output(['ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -1'], shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")

    file.write("8. Больше всего CPU использует:  ")
    output = subprocess.check_output(['ps -eo pcpu,pid,user,args | sort -k 1 -r | head -1'], shell=True)
    file.write(output.decode("utf-8"))
    file.write("\n")
    file.write("\n")
    file.write("========================================================================")
    file.write("\n")
    file.write("\n")
